env:
  global:
  - secure: qcLlbhPDrR+jSbdC7uIKd4FK8lDOrorov15kuK1Ud+FeHB0U1NMjZWRcqLVwKUAAr+oH8fNAODClMZsEuVSaOVJiOJ+t0tMswihTpnwXuU92mPO4yyOAC74HL4uf1MZpewvZWTnuV/AphjYKqsYMBilwXqNeuxpOPYuBYqrDxph0djGWhhQycfFJYlSRzdENCfRpzAe3d0xAqmfQTNpbGeGOPoXMdwc/wu5U4UWRslJba8ekkBBkqzVdI/qDrAmY3WyjE4PwUYKZRE7FjrAXEdtC6SjzFxdJC17s47p96zAorKbznjZtP5Yjc4FnVt44Q0jZfSSH1/hun0NoTppJif5ZAbVbA+CeLZbW49aNhheC5/dIlio8xkdvzmfy2hC/1yJXECUpGodfEvSGg/9ZR0FX0D+e1/ZykVL8/zAC8Wz4nbyQrnDNI1blBs8op3dXS+u6VNM4tfKNrP6W9WB30p1FS39my1AKRddLt0YCJxNxM0jzNNfWZ70pgzRvFroYLSDW5EJyTuEigYdWpuAKiH4CN7XN8DXYbPq2dgtr9+TbUP2hsXSeBFtDLZpnVMAzEJkeA5Fr3hkNHdthnCb6G6vrKW19w2A3ZqZpX204pxPTbLUCB5dJoBl3vOR1ZcFo1eO52FYuVoO0rIXX2DkEYCf/iQXS7TOQU2jnB06drqc=
  - secure: duriYi3zNVTSNDC6YGIKl9cadn/vZgg4F6HmhJ103GPJ3rrOdUXzJ98suRLVfMPFSWw9Ns/sESq2tU+LSEj9BDTWMaxCwKCoEytgrV4EFxm2q2rmTMgx0f+8KErpP9+tXEzz9mjvKjXDoaGuxG9LSeHdj0+4Uf3xPak4sVxFaXNd+477MY5YUXuiSVBUKSymz0oVFAe4Ct3ZBQm9vSNIIrJjjn8clg0oQzPUhkTHghog8wLPZ/Y+Cdc661PJKAFslIxJZsQEYXboPdFOQ6i0PYMfkaP8hPjPZojbAxtqojTR6u1CoADKyN6ggUsTKJSHx7Eak78pbne6Hy1oDcdrDg1es9jJUTrf8x1Fc1+kB8k0oeEuo8qLsxYUYnLdqr5/glzssrtWLxsIVsUavCzDVgy0wNnhU0ZUX6zB3jYWdob9bD4yz0jOOZ3HOjttostbtMpb8vgjKYqYkObUSioGlm1x7wwufWxKAJ967xNAPrYp0LNzGPZOl1Y1gZ0uPuQsM3lGjXfVCrYD0G++S6Lxeayl4+t6oi7JdEzUIyz1HuivrqvCpldpNkC4ghJfBaHWivLSt9RYm5WmIecLIcnhG95+sqQ8l+kEkrvqb3eagphCt7Hd1iF2g7CLMHMjb5Dl6yOhsV9dVljsPnPrH8LN72O8JkEaNt0PvO5s8m+Onr0=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantiqu-1
    token:
      secure: E/5VQ/+wSE2WyjmA5zaPK7nBRkEcCvWWxft9WPBsQaFFMQbjajh0amTK00qZ52GwnOM/yQ/SY5BNy246iCEo/Ks8u3ZuK/mMFlak3iHCNf3a1sh8nvGsNdsGf3fgGMNBg/SzG3Mrl0CTgI+Xcr84ROPU81O5MQo877LCcW1CLxGkBZgPGQPV16bGm2oA7NEW16q9lerjGpQD9A5DlHT4U/gZJQzg5DIqGcAqZhliEkFNCcSkh38nFBt89fIjL217IPRzBFLiy3h5MSHSJtlz7MAl1SlkiJJdoo2Kc0niWUOlNLAuNOtPbcYwSXy5HYWfcnjePnMjl4VC65YWr4pO+0xK1FBZpUq15rvHwqv7qEQDyALrtO183+5yk5TpIPtK+aypUV3+Ma6Ab3gm9XnsnWaFyPHk6EaGeH2yBw/Sh8V8tkSQlj6Uz2pC1hjorZz9NaoU8u0zVC8U6TMq/2G97//mctPPVvVhy52f8h14lGc7ljaBG8IHZiq8LDH2x0eLwUQK9ol5Conqt104ZP1aTUDwHnzKBUd8K45WLd5wetU76PrHusXNs/BxpdPh6QeX46L4jKQdv7PJY2g8P8xdY5p6YZAgPEjhyS/sbz2uCHkY4smz26AwIvtmNoo67KSWXgj3dzjLO17H4UtBnxFV+4YZdFsTrTrvVuo7UPi26gc=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull asfram/jplatformbuild:10sp5

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t asfram/jplatformbuild:10sp5
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: zMA6/a2Lny263EWq7utQV9qcqLJkmLfe3oIMeuyOJMJs0v1SdKiB8tCUQoG6cVI3/vvF0eSGrwkoZg3nn/dybZP08NobGxWYOfHly9XqKAHyJpZZsSbbGJbJ2kQe3af1sJtu+JT5TxoWwO8Eda3fsCxWre2+RdcfxjJCVkjL3a8AJhv+NuEZ0vHrGezgy6K45S7OmfCPiJH2UThT6pXavwCc3JoNTOV+PGTMTTTTKa5FKSlugokVxlsVxwKlapHH9AGRHd+zfsY4VQfjxa1jRU8aieLr30uG1YhRtXoBdwFTowmf5qgqEklyf/Yq9ivGJtEVarDCwEIBNrRu5x6SqVZBynJkwTU/FxZFUj0rzOscr/MABXjlXLm4ZDu/8J3dLDyU/V7/lDjbKxJIjaBFVOUF1uwpLaMc4JmH4CgqVGpXI/p9XaAtSXpfqir8G90YqE2t0jmQEyjIVeXe6+4Sm3D1dAkTaStZAjD1M2aHQI6C4AqDgdhsR+YxTe+26UYtTJbyCdAwDz5N9sxNhXn/QP3Cff8UH4VqanWwCplhJJaveUTR+H+iWBwMwYgDrWtXR8tUtnc5t4CEOHqm0CZBzTnQo5Sq5mDJcUs3lK6cTDr0GtP0qLOKUWghhFi5vReenOMdeCsO4sIo75umQaKpVWOIpuu8vS2STUFadSfyekk=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
