env:
  global:
  - secure: o/uLxN5jHgOeDZN2JhQx8RZprWkWhOJuUXyd3A/CX8AZzE3vfWeXJXrHjDfg42fLr4dFoKScUljgvML67eMe2ZseqCQAWwGbH+rL1YTWUp5u8mp80VTHEkIJPywAbcX9gFOipW9wclVcEBmnr84JKvLazSyCLI6sGKLstHJ/blOAZPvSDueNaWI6WMT9Y+foulq1EJNYzGAWqJdS3K4dD+tic9neeuecRPyNPczFgW1GdC1rgvaiSLl2mxwrAMw4XrmaGnhzjxAT4Q93l13S+qb0Pv87CCW3Emm98ZUhjd8e2L9Mx2XxOOwYXPCSV+0AIc0WSMWL05uxTV3lmWZX2AftKSYXQinuVtt6z+0L9wbrqzgZueMt3v+WVqVFa05n56i1OEwFEwqqqnn4f+ewZ5/UkRAdsQHVN1djlpskD+Uy8YZvZ5zNzkIupvqmcr9k5O1AZ1uj3I78zWPgIZwbLwOLrHFAiFO+M2jw+Oe2abSkiwmKKmGRD3N8v4tBcd8loPXE/w6qlr+Ui0SgF2MO54W3nuqC9G6KyK50b0bgBjYDnr5D8cyfhuRA0jvx9cW53nKP6Mjzih/bqifa0zjtrRL3H73iM1CY6+G+pERnuKrzxyCo2wmqhj5Vju/mEYqtxMVBhrxXIWUBo2EqGoS/mo1zCE6MuOyz+uSNdsdDgJg=
  - secure: AyXN/2UVjZY+5kulUA/IOlfYFC2U1xt5by/c7FlAI3IenmkqptfkfSUTJZFAq7rEQ217TSQkRbi2eX/iU9WYT7Fja2cGwwy5fBHQwvoUeebMBzVH3O433GG04YRB8aHBXsVo0TDqTAVWpKvLGH1faJ9ZFWdRQz5hF0uHpd7cX+meTef5BU5GNHrvm5rQUcLI5iA8YRR13a7QoszRQfN9gHdjQ7nda0A0hg/J+t2/vPGzYZKIEyMYqA/dDJ+o/PIfaYR2VS7vS4tkpoMkdxxcH6vFkTh1WyZmHWMiCbT9DbPtRGRVupy7slWXIyr4/49UG3/jJmpTVehPn4anjQOEHAJ0bjcpddjVIEo3SQEwPpUKlNV+RdhVMng+YVQZzvlBDR/vQZ61QLgBHi2HR8D9c9GScAbpuUIwaIr7Owf0Sp0h2XjPa+2kUO7bLndRTZHrB1wv/6P8jVSee7vlzZho/dirGVto3ZloaLgKc2Lp7r9NQjnhV6BrjHecfX9i0AqJzhhwbD6OtF9j+bk4ISwhlqDt9kPNVw3621sQtjY6oAVCmrKaPnd1X4trc7/kd5iS+EI2yZeGccGs4G01dge1k+OM0EtxBM7sspVynhR30wIZjbFXHkAANvhAf4njNpuYB6AeWniHa0V9rfy3+pTXA2eru2M/0qZPi0MICCnQ07A=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantiqu-1
    token:
      secure: E/5VQ/+wSE2WyjmA5zaPK7nBRkEcCvWWxft9WPBsQaFFMQbjajh0amTK00qZ52GwnOM/yQ/SY5BNy246iCEo/Ks8u3ZuK/mMFlak3iHCNf3a1sh8nvGsNdsGf3fgGMNBg/SzG3Mrl0CTgI+Xcr84ROPU81O5MQo877LCcW1CLxGkBZgPGQPV16bGm2oA7NEW16q9lerjGpQD9A5DlHT4U/gZJQzg5DIqGcAqZhliEkFNCcSkh38nFBt89fIjL217IPRzBFLiy3h5MSHSJtlz7MAl1SlkiJJdoo2Kc0niWUOlNLAuNOtPbcYwSXy5HYWfcnjePnMjl4VC65YWr4pO+0xK1FBZpUq15rvHwqv7qEQDyALrtO183+5yk5TpIPtK+aypUV3+Ma6Ab3gm9XnsnWaFyPHk6EaGeH2yBw/Sh8V8tkSQlj6Uz2pC1hjorZz9NaoU8u0zVC8U6TMq/2G97//mctPPVvVhy52f8h14lGc7ljaBG8IHZiq8LDH2x0eLwUQK9ol5Conqt104ZP1aTUDwHnzKBUd8K45WLd5wetU76PrHusXNs/BxpdPh6QeX46L4jKQdv7PJY2g8P8xdY5p6YZAgPEjhyS/sbz2uCHkY4smz26AwIvtmNoo67KSWXgj3dzjLO17H4UtBnxFV+4YZdFsTrTrvVuo7UPi26gc=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull sguellec/jplatformbuild

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t sguellec/jplatformbuild
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: zMA6/a2Lny263EWq7utQV9qcqLJkmLfe3oIMeuyOJMJs0v1SdKiB8tCUQoG6cVI3/vvF0eSGrwkoZg3nn/dybZP08NobGxWYOfHly9XqKAHyJpZZsSbbGJbJ2kQe3af1sJtu+JT5TxoWwO8Eda3fsCxWre2+RdcfxjJCVkjL3a8AJhv+NuEZ0vHrGezgy6K45S7OmfCPiJH2UThT6pXavwCc3JoNTOV+PGTMTTTTKa5FKSlugokVxlsVxwKlapHH9AGRHd+zfsY4VQfjxa1jRU8aieLr30uG1YhRtXoBdwFTowmf5qgqEklyf/Yq9ivGJtEVarDCwEIBNrRu5x6SqVZBynJkwTU/FxZFUj0rzOscr/MABXjlXLm4ZDu/8J3dLDyU/V7/lDjbKxJIjaBFVOUF1uwpLaMc4JmH4CgqVGpXI/p9XaAtSXpfqir8G90YqE2t0jmQEyjIVeXe6+4Sm3D1dAkTaStZAjD1M2aHQI6C4AqDgdhsR+YxTe+26UYtTJbyCdAwDz5N9sxNhXn/QP3Cff8UH4VqanWwCplhJJaveUTR+H+iWBwMwYgDrWtXR8tUtnc5t4CEOHqm0CZBzTnQo5Sq5mDJcUs3lK6cTDr0GtP0qLOKUWghhFi5vReenOMdeCsO4sIo75umQaKpVWOIpuu8vS2STUFadSfyekk=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
