package fr.cg44.plugin.assmat.beans;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.vividsolutions.jts.geom.Point;

import fr.cg44.plugin.assmat.AssmatUtil;


/**
 * AssmatSearch generated by hbm2java
 */
public class AssmatSearch implements java.io.Serializable, Comparable<AssmatSearch> {

	private long JRowId;
	private Boolean isDomicile;
	private Boolean accueilPeriscolaire;
	private Boolean accueilMercredi;
	private Boolean accueilVacances;
	private Boolean accueilAvant7h;
	private Boolean accueilApres20h;
	private Boolean accueilSamedi;
	private Boolean accueilDimanche;
	private Boolean accueilNuit;
	private Boolean accueilAtypique;
	private Boolean specHandicape;
	private Boolean specPartiel;
	private Boolean specDepannages;
	private Date debutAccueil;
	private Integer placesDispos;
	private String nomAssmat;
	private Boolean accepteContact;
	private Integer commune;
	private Double latitude;
	private Double longitude;
	private Point geometry;
	private Long JRowProfilam;
	private String membreJcmsId;
	private String dbprofilId;
	private long JRowSolisId;
	private String idMicroQuartier;
	

	private Set<DispoAssmat> dispoAssmats = new HashSet<DispoAssmat>(0);

	public AssmatSearch() {
	}

	public AssmatSearch( Boolean isDomicile, Boolean accueilPeriscolaire, Boolean accueilMercredi, Boolean accueilVacances, Boolean accueilAvant7h, Boolean accueilApres20h, Boolean accueilSamedi, Boolean accueilDimanche, Boolean accueilNuit, Boolean accueilAtypique, Boolean specHandicape, Boolean specPartiel, Boolean specDepannages, Date debutAccueil, Integer placesDispos, String nomAssmat, Boolean accepteContact, Integer commune, Double latitude, Double longitude,
			Long JRowProfilam, String membreJcmsId, String dbprofilId, long JRowSolisId, String idMicroQuartier, Set<DispoAssmat> dispoAssmats) {
		this.isDomicile = isDomicile;
		this.accueilPeriscolaire = accueilPeriscolaire;
		this.accueilMercredi = accueilMercredi;
		this.accueilVacances = accueilVacances;
		this.accueilAvant7h = accueilAvant7h;
		this.accueilApres20h = accueilApres20h;
		this.accueilSamedi = accueilSamedi;
		this.accueilDimanche = accueilDimanche;
		this.accueilNuit = accueilNuit;
		this.accueilAtypique = accueilAtypique;
		this.specHandicape = specHandicape;
		this.specPartiel = specPartiel;
		this.specDepannages = specDepannages;
		this.debutAccueil = debutAccueil;
		this.placesDispos = placesDispos;
		this.nomAssmat = nomAssmat;
		this.accepteContact = accepteContact;
		this.commune = commune;
		this.latitude = latitude;
		this.longitude = longitude;

		this.JRowProfilam = JRowProfilam;
		this.membreJcmsId = membreJcmsId;
		this.dbprofilId = dbprofilId;
		this.JRowSolisId = JRowSolisId;
		this.idMicroQuartier = idMicroQuartier;
		this.dispoAssmats = dispoAssmats;
	
		this.geometry = AssmatUtil.getGeometry( latitude, longitude);		
	}
	
	
	

	public long getJRowId() {
		return this.JRowId;
	}

	public void setJRowId(long JRowId) {
		this.JRowId = JRowId;
	}

	public Boolean getIsDomicile() {
		return this.isDomicile;
	}

	public void setIsDomicile(Boolean isDomicile) {
		this.isDomicile = isDomicile;
	}

	public Boolean getAccueilPeriscolaire() {
		return this.accueilPeriscolaire;
	}

	public void setAccueilPeriscolaire(Boolean accueilPeriscolaire) {
		this.accueilPeriscolaire = accueilPeriscolaire;
	}

	public Boolean getAccueilMercredi() {
		return this.accueilMercredi;
	}

	public void setAccueilMercredi(Boolean accueilMercredi) {
		this.accueilMercredi = accueilMercredi;
	}

	public Boolean getAccueilVacances() {
		return this.accueilVacances;
	}

	public void setAccueilVacances(Boolean accueilVacances) {
		this.accueilVacances = accueilVacances;
	}

	public Boolean getAccueilAvant7h() {
		return this.accueilAvant7h;
	}

	public void setAccueilAvant7h(Boolean accueilAvant7h) {
		this.accueilAvant7h = accueilAvant7h;
	}

	public Boolean getAccueilApres20h() {
		return this.accueilApres20h;
	}

	public void setAccueilApres20h(Boolean accueilApres20h) {
		this.accueilApres20h = accueilApres20h;
	}

	public Boolean getAccueilSamedi() {
		return this.accueilSamedi;
	}

	public void setAccueilSamedi(Boolean accueilSamedi) {
		this.accueilSamedi = accueilSamedi;
	}

	public Boolean getAccueilDimanche() {
		return this.accueilDimanche;
	}

	public void setAccueilDimanche(Boolean accueilDimanche) {
		this.accueilDimanche = accueilDimanche;
	}

	public Boolean getAccueilNuit() {
		return this.accueilNuit;
	}

	public void setAccueilNuit(Boolean accueilNuit) {
		this.accueilNuit = accueilNuit;
	}

	public Boolean getAccueilAtypique() {
		return this.accueilAtypique;
	}

	public void setAccueilAtypique(Boolean accueilAtypique) {
		this.accueilAtypique = accueilAtypique;
	}

	public Boolean getSpecHandicape() {
		return this.specHandicape;
	}

	public void setSpecHandicape(Boolean specHandicape) {
		this.specHandicape = specHandicape;
	}

	public Boolean getSpecPartiel() {
		return this.specPartiel;
	}

	public void setSpecPartiel(Boolean specPartiel) {
		this.specPartiel = specPartiel;
	}

	public Boolean getSpecDepannages() {
		return this.specDepannages;
	}

	public void setSpecDepannages(Boolean specDepannages) {
		this.specDepannages = specDepannages;
	}

	public Date getDebutAccueil() {
		return this.debutAccueil;
	}

	public void setDebutAccueil(Date debutAccueil) {
		this.debutAccueil = debutAccueil;
	}

	public Integer getPlacesDispos() {
		return this.placesDispos;
	}

	public void setPlacesDispos(Integer placesDispos) {
		this.placesDispos = placesDispos;
	}

	public String getNomAssmat() {
		return this.nomAssmat;
	}

	public void setNomAssmat(String nomAssmat) {
		this.nomAssmat = nomAssmat;
	}

	public Boolean getAccepteContact() {
		return this.accepteContact;
	}

	public void setAccepteContact(Boolean accepteContact) {
		this.accepteContact = accepteContact;
	}

	public Integer getCommune() {
		return this.commune;
	}

	public void setCommune(Integer commune) {
		this.commune = commune;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	  public Point getGeometry() {
		    return geometry;
		  }

		  public void setGeometry(Point geometry) {
		    this.geometry = geometry;
		  }

	public Long getJRowProfilam() {
		return this.JRowProfilam;
	}

	public void setJRowProfilam(Long JRowProfilam) {
		this.JRowProfilam = JRowProfilam;
	}

	public String getMembreJcmsId() {
		return this.membreJcmsId;
	}

	public void setMembreJcmsId(String membreJcmsId) {
		this.membreJcmsId = membreJcmsId;
	}

	public String getDbprofilId() {
		return this.dbprofilId;
	}

	public void setDbprofilId(String dbprofilId) {
		this.dbprofilId = dbprofilId;
	}

	public long getJRowSolisId() {
		return this.JRowSolisId;
	}

	public void setJRowSolisId(long JRowSolisId) {
		this.JRowSolisId = JRowSolisId;
	}
	
	public String getIdMicroQuartier() {
		return idMicroQuartier;
	}

	public void setIdMicroQuartier(String idMicroQuartier) {
		this.idMicroQuartier = idMicroQuartier;
	}

	public Set<DispoAssmat> getDispoAssmats() {
		return this.dispoAssmats;
	}

	public void setDispoAssmats(Set<DispoAssmat> dispoAssmats) {
		this.dispoAssmats = dispoAssmats;
	}

	@Override
	public int compareTo(AssmatSearch o) {	
		if(o.getJRowId() == JRowId)
			return 0;		
		return -1;
	}
	
	@Override
	public boolean equals(Object obj) {
	  if(obj instanceof AssmatSearch) {
	    AssmatSearch assmatSearch = (AssmatSearch) obj; 
	    return JRowId == assmatSearch.getJRowId();
	  }
	  return false;
	}
	
 @Override
 public int hashCode() {   
   return (int) (JRowId ^ (JRowId >>> 32)); 
 }

}
