package fr.cg44.plugin.assmat.beans;

import java.util.Date;

/**
 * DispoAssmat generated by hbm2java
 */
public class DispoAssmat implements java.io.Serializable {

	private long JItemId;
	private AssmatSearch assmatSearch;
	private Integer trancheAgeKey;
	private Date dateDebut;
	private String assmatId;
	private String jcmsId;
	private String disponible;

	public DispoAssmat() {
	}


	public DispoAssmat(AssmatSearch assmatSearch, Integer trancheAgeKey, Date dateDebut, String assmatId, String jcmsId, String disponible) {
		this.assmatSearch = assmatSearch;
		this.trancheAgeKey = trancheAgeKey;
		this.dateDebut = dateDebut;
		this.assmatId = assmatId;
		this.jcmsId = jcmsId;
		this.disponible = disponible;
	}

	public long getJItemId() {
		return this.JItemId;
	}

	public void setJItemId(long JItemId) {
		this.JItemId = JItemId;
	}

	public AssmatSearch getAssmatSearch() {
		return this.assmatSearch;
	}

	public void setAssmatSearch(AssmatSearch assmatSearch) {
		this.assmatSearch = assmatSearch;
	}

	public Integer getTrancheAgeKey() {
		return this.trancheAgeKey;
	}

	public void setTrancheAgeKey(Integer trancheAgeKey) {
		this.trancheAgeKey = trancheAgeKey;
	}

	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	public String getAssmatId() {
		return this.assmatId;
	}

	public void setAssmatId(String assmatId) {
		this.assmatId = assmatId;
	}

	public String getJcmsId() {
		return this.jcmsId;
	}

	public void setJcmsId(String jcmsId) {
		this.jcmsId = jcmsId;
	}

	public String getDisponible() {
		return this.disponible;
	}

	public void setDisponible(String disponible) {
		this.disponible = disponible;
	}

}
