package fr.cg44.plugin.assmat.beans;

// Generated 2 nov. 2016 15:03:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EnvoiSms generated by hbm2java
 */
public class EnvoiSms implements java.io.Serializable {

	private Long id;
	private Date createdDate;
	private Date updatedDate;
	private String custId;
	private String login;
	private String assmatId;
	private String sendProfiles;
	private String subject;
	private String content;
	private String stragegy;
	private String idDiffusion;
	private String lastErrorCode;
	private String statutDiffusion;
	private String resumeContent;

	public EnvoiSms() {
	}

	public EnvoiSms(Date createdDate, Date updatedDate, String custId, String login, String assmatId, String sendProfiles, String subject, String content, String stragegy, String idDiffusion, String lastErrorCode, String statutDiffusion, String resumeContent) {
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.custId = custId;
		this.login = login;
		this.assmatId = assmatId;
		this.sendProfiles = sendProfiles;
		this.subject = subject;
		this.content = content;
		this.stragegy = stragegy;
		this.idDiffusion = idDiffusion;
		this.lastErrorCode = lastErrorCode;
		this.statutDiffusion = statutDiffusion;
		this.resumeContent = resumeContent;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getCustId() {
		return this.custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getAssmatId() {
		return this.assmatId;
	}

	public void setAssmatId(String assmatId) {
		this.assmatId = assmatId;
	}

	public String getSendProfiles() {
		return this.sendProfiles;
	}

	public void setSendProfiles(String sendProfiles) {
		this.sendProfiles = sendProfiles;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getStragegy() {
		return this.stragegy;
	}

	public void setStragegy(String stragegy) {
		this.stragegy = stragegy;
	}

	public String getIdDiffusion() {
		return this.idDiffusion;
	}

	public void setIdDiffusion(String idDiffusion) {
		this.idDiffusion = idDiffusion;
	}

	public String getLastErrorCode() {
		return this.lastErrorCode;
	}

	public void setLastErrorCode(String lastErrorCode) {
		this.lastErrorCode = lastErrorCode;
	}

	public String getStatutDiffusion() {
		return this.statutDiffusion;
	}

	public void setStatutDiffusion(String statutDiffusion) {
		this.statutDiffusion = statutDiffusion;
	}

	public String getResumeContent() {
		return this.resumeContent;
	}

	public void setResumeContent(String resumeContent) {
		this.resumeContent = resumeContent;
	}

}
