package fr.cg44.plugin.assmat.beans;

// Generated 2 nov. 2016 15:03:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TrsbActivation generated by hbm2java
 */
public class TrsbActivation implements java.io.Serializable {

	private Integer JRowId;
	private int typeActivation;
	private Integer codeConfirmation;
	private Date dateExpiration;
	private String inscriptionId;

	public TrsbActivation() {
	}

	public TrsbActivation(int typeActivation) {
		this.typeActivation = typeActivation;
	}

	public TrsbActivation(int typeActivation, Integer codeConfirmation, Date dateExpiration, String inscriptionId) {
		this.typeActivation = typeActivation;
		this.codeConfirmation = codeConfirmation;
		this.dateExpiration = dateExpiration;
		this.inscriptionId = inscriptionId;
	}

	public Integer getJRowId() {
		return this.JRowId;
	}

	public void setJRowId(Integer JRowId) {
		this.JRowId = JRowId;
	}

	public int getTypeActivation() {
		return this.typeActivation;
	}

	public void setTypeActivation(int typeActivation) {
		this.typeActivation = typeActivation;
	}

	public Integer getCodeConfirmation() {
		return this.codeConfirmation;
	}

	public void setCodeConfirmation(Integer codeConfirmation) {
		this.codeConfirmation = codeConfirmation;
	}

	public Date getDateExpiration() {
		return this.dateExpiration;
	}

	public void setDateExpiration(Date dateExpiration) {
		this.dateExpiration = dateExpiration;
	}

	public String getInscriptionId() {
		return this.inscriptionId;
	}

	public void setInscriptionId(String inscriptionId) {
		this.inscriptionId = inscriptionId;
	}

}
